const colorText = document.getElementById('color-text');
const scoreText = document.getElementById('score-text');
const maxScoreText = document.getElementById('max-score-text')
const redButton = document.getElementById('red-button');
const orangeButton = document.getElementById('orange-button');
const yellowButton = document.getElementById('yellow-button');
const greenButton = document.getElementById('green-button');
const blueButton = document.getElementById('blue-button');
const pinkButton = document.getElementById('pink-button');
const purpleButton = document.getElementById('purple-button');
const brownButton = document.getElementById('brown-button');
const blackButton = document.getElementById('black-button');
const GameStartButton = document.getElementById('test-button')

redButton.style.backgroundColor = 'red'; 
orangeButton.style.backgroundColor = 'orange';
yellowButton.style.backgroundColor = 'yellow';
greenButton.style.backgroundColor = 'green';
blueButton.style.backgroundColor = 'blue';
pinkButton.style.backgroundColor = 'pink';
purpleButton.style.backgroundColor = 'purple';
brownButton.style.backgroundColor = 'brown';
blackButton.style.backgroundColor = 'black'